// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shrike.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Cause struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cause) Reset()         { *m = Cause{} }
func (m *Cause) String() string { return proto.CompactTextString(m) }
func (*Cause) ProtoMessage()    {}
func (*Cause) Descriptor() ([]byte, []int) {
	return fileDescriptor_shrike_d6e7affa99f49da6, []int{0}
}
func (m *Cause) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cause.Unmarshal(m, b)
}
func (m *Cause) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cause.Marshal(b, m, deterministic)
}
func (dst *Cause) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cause.Merge(dst, src)
}
func (m *Cause) XXX_Size() int {
	return xxx_messageInfo_Cause.Size(m)
}
func (m *Cause) XXX_DiscardUnknown() {
	xxx_messageInfo_Cause.DiscardUnknown(m)
}

var xxx_messageInfo_Cause proto.InternalMessageInfo

func (m *Cause) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Cause) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CreateCauseRequest struct {
	Item                 *Cause   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCauseRequest) Reset()         { *m = CreateCauseRequest{} }
func (m *CreateCauseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCauseRequest) ProtoMessage()    {}
func (*CreateCauseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shrike_d6e7affa99f49da6, []int{1}
}
func (m *CreateCauseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCauseRequest.Unmarshal(m, b)
}
func (m *CreateCauseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCauseRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCauseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCauseRequest.Merge(dst, src)
}
func (m *CreateCauseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCauseRequest.Size(m)
}
func (m *CreateCauseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCauseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCauseRequest proto.InternalMessageInfo

func (m *CreateCauseRequest) GetItem() *Cause {
	if m != nil {
		return m.Item
	}
	return nil
}

type CreateCauseResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCauseResponse) Reset()         { *m = CreateCauseResponse{} }
func (m *CreateCauseResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCauseResponse) ProtoMessage()    {}
func (*CreateCauseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_shrike_d6e7affa99f49da6, []int{2}
}
func (m *CreateCauseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCauseResponse.Unmarshal(m, b)
}
func (m *CreateCauseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCauseResponse.Marshal(b, m, deterministic)
}
func (dst *CreateCauseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCauseResponse.Merge(dst, src)
}
func (m *CreateCauseResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCauseResponse.Size(m)
}
func (m *CreateCauseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCauseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCauseResponse proto.InternalMessageInfo

func (m *CreateCauseResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetCauseRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCauseRequest) Reset()         { *m = GetCauseRequest{} }
func (m *GetCauseRequest) String() string { return proto.CompactTextString(m) }
func (*GetCauseRequest) ProtoMessage()    {}
func (*GetCauseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shrike_d6e7affa99f49da6, []int{3}
}
func (m *GetCauseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCauseRequest.Unmarshal(m, b)
}
func (m *GetCauseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCauseRequest.Marshal(b, m, deterministic)
}
func (dst *GetCauseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCauseRequest.Merge(dst, src)
}
func (m *GetCauseRequest) XXX_Size() int {
	return xxx_messageInfo_GetCauseRequest.Size(m)
}
func (m *GetCauseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCauseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCauseRequest proto.InternalMessageInfo

func (m *GetCauseRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetCauseResponse struct {
	Item                 *Cause   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCauseResponse) Reset()         { *m = GetCauseResponse{} }
func (m *GetCauseResponse) String() string { return proto.CompactTextString(m) }
func (*GetCauseResponse) ProtoMessage()    {}
func (*GetCauseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_shrike_d6e7affa99f49da6, []int{4}
}
func (m *GetCauseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCauseResponse.Unmarshal(m, b)
}
func (m *GetCauseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCauseResponse.Marshal(b, m, deterministic)
}
func (dst *GetCauseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCauseResponse.Merge(dst, src)
}
func (m *GetCauseResponse) XXX_Size() int {
	return xxx_messageInfo_GetCauseResponse.Size(m)
}
func (m *GetCauseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCauseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCauseResponse proto.InternalMessageInfo

func (m *GetCauseResponse) GetItem() *Cause {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*Cause)(nil), "shrike.v1.Cause")
	proto.RegisterType((*CreateCauseRequest)(nil), "shrike.v1.CreateCauseRequest")
	proto.RegisterType((*CreateCauseResponse)(nil), "shrike.v1.CreateCauseResponse")
	proto.RegisterType((*GetCauseRequest)(nil), "shrike.v1.GetCauseRequest")
	proto.RegisterType((*GetCauseResponse)(nil), "shrike.v1.GetCauseResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShrikeServiceClient is the client API for ShrikeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShrikeServiceClient interface {
	CreateCause(ctx context.Context, in *CreateCauseRequest, opts ...grpc.CallOption) (*CreateCauseResponse, error)
	GetCause(ctx context.Context, in *GetCauseRequest, opts ...grpc.CallOption) (*GetCauseResponse, error)
}

type shrikeServiceClient struct {
	cc *grpc.ClientConn
}

func NewShrikeServiceClient(cc *grpc.ClientConn) ShrikeServiceClient {
	return &shrikeServiceClient{cc}
}

func (c *shrikeServiceClient) CreateCause(ctx context.Context, in *CreateCauseRequest, opts ...grpc.CallOption) (*CreateCauseResponse, error) {
	out := new(CreateCauseResponse)
	err := c.cc.Invoke(ctx, "/shrike.v1.ShrikeService/CreateCause", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shrikeServiceClient) GetCause(ctx context.Context, in *GetCauseRequest, opts ...grpc.CallOption) (*GetCauseResponse, error) {
	out := new(GetCauseResponse)
	err := c.cc.Invoke(ctx, "/shrike.v1.ShrikeService/GetCause", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShrikeServiceServer is the server API for ShrikeService service.
type ShrikeServiceServer interface {
	CreateCause(context.Context, *CreateCauseRequest) (*CreateCauseResponse, error)
	GetCause(context.Context, *GetCauseRequest) (*GetCauseResponse, error)
}

func RegisterShrikeServiceServer(s *grpc.Server, srv ShrikeServiceServer) {
	s.RegisterService(&_ShrikeService_serviceDesc, srv)
}

func _ShrikeService_CreateCause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServiceServer).CreateCause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.v1.ShrikeService/CreateCause",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServiceServer).CreateCause(ctx, req.(*CreateCauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShrikeService_GetCause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShrikeServiceServer).GetCause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shrike.v1.ShrikeService/GetCause",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShrikeServiceServer).GetCause(ctx, req.(*GetCauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShrikeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shrike.v1.ShrikeService",
	HandlerType: (*ShrikeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCause",
			Handler:    _ShrikeService_CreateCause_Handler,
		},
		{
			MethodName: "GetCause",
			Handler:    _ShrikeService_GetCause_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shrike.proto",
}

func init() { proto.RegisterFile("shrike.proto", fileDescriptor_shrike_d6e7affa99f49da6) }

var fileDescriptor_shrike_d6e7affa99f49da6 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x8e, 0xd3, 0x30,
	0x14, 0x85, 0xe5, 0x74, 0x7e, 0xa8, 0x87, 0x29, 0x95, 0x67, 0x84, 0x46, 0xe1, 0x47, 0x26, 0x02,
	0x34, 0xaa, 0x68, 0x3c, 0x2d, 0x5d, 0xa0, 0xb2, 0x01, 0x2a, 0xc1, 0x3e, 0xdd, 0x01, 0x9b, 0x34,
	0xb9, 0x4a, 0x0c, 0xad, 0x6d, 0xec, 0x9b, 0x0c, 0x12, 0x62, 0xc3, 0x23, 0xc0, 0x8e, 0xc7, 0x61,
	0xc9, 0x0a, 0x89, 0x57, 0xe0, 0x41, 0x10, 0x4e, 0x18, 0x3a, 0x53, 0x90, 0x58, 0x45, 0xbe, 0xe7,
	0x3b, 0x27, 0xe7, 0x4a, 0x97, 0x5e, 0x76, 0xa5, 0x95, 0xaf, 0x21, 0x36, 0x56, 0xa3, 0x66, 0xdd,
	0xf6, 0x55, 0x8f, 0xc2, 0xeb, 0x85, 0xd6, 0xc5, 0x12, 0x44, 0x6a, 0xa4, 0x48, 0x95, 0xd2, 0x98,
	0xa2, 0xd4, 0xca, 0x35, 0x60, 0x78, 0xcf, 0x7f, 0xb2, 0x61, 0x01, 0x6a, 0xe8, 0x4e, 0xd3, 0xa2,
	0x00, 0x2b, 0xb4, 0xf1, 0xc4, 0x26, 0x1d, 0x0d, 0xe9, 0xf6, 0x2c, 0xad, 0x1c, 0xb0, 0x1e, 0x0d,
	0x64, 0x7e, 0x44, 0x38, 0x39, 0xee, 0x24, 0x81, 0xcc, 0xd9, 0x21, 0xdd, 0x46, 0x89, 0x4b, 0x38,
	0x0a, 0x38, 0x39, 0xee, 0x26, 0xcd, 0x23, 0x9a, 0x52, 0x36, 0xb3, 0x90, 0x22, 0x78, 0x53, 0x02,
	0x6f, 0x2a, 0x70, 0xc8, 0x6e, 0xd3, 0x2d, 0x89, 0xb0, 0xf2, 0xee, 0xbd, 0x71, 0x3f, 0x3e, 0xab,
	0x1a, 0x37, 0x98, 0x57, 0xa3, 0x3b, 0xf4, 0xe0, 0x9c, 0xd7, 0x19, 0xad, 0x36, 0x7f, 0x1c, 0xdd,
	0xa2, 0x57, 0x9e, 0x01, 0x9e, 0xcb, 0xbf, 0x88, 0x3c, 0xa0, 0xfd, 0x3f, 0x48, 0x1b, 0xf3, 0x5f,
	0x1d, 0xc6, 0xdf, 0x08, 0xdd, 0x9f, 0x7b, 0x65, 0x0e, 0xb6, 0x96, 0x19, 0xb0, 0x05, 0xdd, 0x5b,
	0x6b, 0xc5, 0x6e, 0xac, 0x1b, 0x37, 0x36, 0x0d, 0x6f, 0xfe, 0x4b, 0x6e, 0x5a, 0x44, 0x87, 0x1f,
	0xbe, 0xff, 0xf8, 0x14, 0xf4, 0xa2, 0xae, 0xa8, 0x47, 0x22, 0xfb, 0x25, 0x4d, 0xc9, 0x80, 0xbd,
	0xa0, 0x97, 0x7e, 0xf7, 0x65, 0xe1, 0x5a, 0xc2, 0x85, 0x3d, 0xc3, 0x6b, 0x7f, 0xd5, 0xda, 0xe8,
	0xab, 0x3e, 0xba, 0xcf, 0x7a, 0x67, 0xd1, 0xe2, 0x9d, 0xcc, 0xdf, 0x3f, 0xf9, 0x4a, 0x3e, 0x3e,
	0xfe, 0x42, 0xd8, 0x4b, 0xba, 0xef, 0x79, 0xee, 0x9a, 0xc5, 0xa2, 0xa7, 0x74, 0x57, 0x1b, 0x50,
	0x2b, 0xbd, 0x60, 0x77, 0x4b, 0x44, 0xe3, 0xa6, 0x42, 0x14, 0x12, 0xcb, 0x6a, 0x11, 0x67, 0x7a,
	0x25, 0xe6, 0x08, 0x35, 0xcc, 0x52, 0x87, 0x4b, 0x10, 0x2d, 0x17, 0x1e, 0x38, 0x04, 0x53, 0x82,
	0x7a, 0xd4, 0x0e, 0x62, 0x6d, 0x8b, 0x71, 0x67, 0x14, 0x9f, 0x0c, 0x08, 0x19, 0xf7, 0x53, 0x63,
	0x96, 0x32, 0xf3, 0xd7, 0x23, 0x5e, 0x39, 0xad, 0xa6, 0x1b, 0x93, 0xe4, 0x21, 0xed, 0x4c, 0x4e,
	0x26, 0x6c, 0x42, 0x07, 0x09, 0x60, 0x65, 0x15, 0xe4, 0xfc, 0xb4, 0x04, 0xc5, 0xb1, 0x04, 0x6e,
	0xc1, 0xe9, 0xca, 0x66, 0xc0, 0x73, 0x0d, 0x8e, 0x2b, 0x8d, 0x1c, 0xde, 0x4a, 0x87, 0x31, 0xdb,
	0xa1, 0x5b, 0x9f, 0x03, 0xb2, 0xfb, 0x3c, 0xa8, 0x47, 0x8b, 0x1d, 0x7f, 0x95, 0xf7, 0x7f, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x5b, 0x41, 0xce, 0x40, 0xfc, 0x02, 0x00, 0x00,
}
