// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDistricts(t *testing.T) {
	t.Parallel()

	query := Districts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDistrictsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &District{}
	if err = randomize.Struct(seed, o, districtDBTypes, true, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Districts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDistrictsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &District{}
	if err = randomize.Struct(seed, o, districtDBTypes, true, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Districts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Districts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDistrictsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &District{}
	if err = randomize.Struct(seed, o, districtDBTypes, true, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DistrictSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Districts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDistrictsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &District{}
	if err = randomize.Struct(seed, o, districtDBTypes, true, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DistrictExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if District exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DistrictExists to return true, but got false.")
	}
}

func testDistrictsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &District{}
	if err = randomize.Struct(seed, o, districtDBTypes, true, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	districtFound, err := FindDistrict(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if districtFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDistrictsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &District{}
	if err = randomize.Struct(seed, o, districtDBTypes, true, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Districts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDistrictsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &District{}
	if err = randomize.Struct(seed, o, districtDBTypes, true, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Districts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDistrictsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	districtOne := &District{}
	districtTwo := &District{}
	if err = randomize.Struct(seed, districtOne, districtDBTypes, false, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}
	if err = randomize.Struct(seed, districtTwo, districtDBTypes, false, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = districtOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = districtTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Districts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDistrictsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	districtOne := &District{}
	districtTwo := &District{}
	if err = randomize.Struct(seed, districtOne, districtDBTypes, false, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}
	if err = randomize.Struct(seed, districtTwo, districtDBTypes, false, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = districtOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = districtTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Districts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func districtBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *District) error {
	*o = District{}
	return nil
}

func districtAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *District) error {
	*o = District{}
	return nil
}

func districtAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *District) error {
	*o = District{}
	return nil
}

func districtBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *District) error {
	*o = District{}
	return nil
}

func districtAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *District) error {
	*o = District{}
	return nil
}

func districtBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *District) error {
	*o = District{}
	return nil
}

func districtAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *District) error {
	*o = District{}
	return nil
}

func districtBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *District) error {
	*o = District{}
	return nil
}

func districtAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *District) error {
	*o = District{}
	return nil
}

func testDistrictsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &District{}
	o := &District{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, districtDBTypes, false); err != nil {
		t.Errorf("Unable to randomize District object: %s", err)
	}

	AddDistrictHook(boil.BeforeInsertHook, districtBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	districtBeforeInsertHooks = []DistrictHook{}

	AddDistrictHook(boil.AfterInsertHook, districtAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	districtAfterInsertHooks = []DistrictHook{}

	AddDistrictHook(boil.AfterSelectHook, districtAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	districtAfterSelectHooks = []DistrictHook{}

	AddDistrictHook(boil.BeforeUpdateHook, districtBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	districtBeforeUpdateHooks = []DistrictHook{}

	AddDistrictHook(boil.AfterUpdateHook, districtAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	districtAfterUpdateHooks = []DistrictHook{}

	AddDistrictHook(boil.BeforeDeleteHook, districtBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	districtBeforeDeleteHooks = []DistrictHook{}

	AddDistrictHook(boil.AfterDeleteHook, districtAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	districtAfterDeleteHooks = []DistrictHook{}

	AddDistrictHook(boil.BeforeUpsertHook, districtBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	districtBeforeUpsertHooks = []DistrictHook{}

	AddDistrictHook(boil.AfterUpsertHook, districtAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	districtAfterUpsertHooks = []DistrictHook{}
}

func testDistrictsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &District{}
	if err = randomize.Struct(seed, o, districtDBTypes, true, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Districts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDistrictsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &District{}
	if err = randomize.Struct(seed, o, districtDBTypes, true); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(districtColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Districts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDistrictsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &District{}
	if err = randomize.Struct(seed, o, districtDBTypes, true, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDistrictsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &District{}
	if err = randomize.Struct(seed, o, districtDBTypes, true, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DistrictSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDistrictsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &District{}
	if err = randomize.Struct(seed, o, districtDBTypes, true, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Districts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	districtDBTypes = map[string]string{`CreatedAt`: `timestamp without time zone`, `ID`: `integer`, `UpdatedAt`: `timestamp without time zone`}
	_               = bytes.MinRead
)

func testDistrictsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(districtPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(districtColumns) == len(districtPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &District{}
	if err = randomize.Struct(seed, o, districtDBTypes, true, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Districts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, districtDBTypes, true, districtPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDistrictsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(districtColumns) == len(districtPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &District{}
	if err = randomize.Struct(seed, o, districtDBTypes, true, districtColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Districts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, districtDBTypes, true, districtPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(districtColumns, districtPrimaryKeyColumns) {
		fields = districtColumns
	} else {
		fields = strmangle.SetComplement(
			districtColumns,
			districtPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DistrictSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testDistrictsUpsert(t *testing.T) {
	t.Parallel()

	if len(districtColumns) == len(districtPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := District{}
	if err = randomize.Struct(seed, &o, districtDBTypes, true); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert District: %s", err)
	}

	count, err := Districts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, districtDBTypes, false, districtPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize District struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert District: %s", err)
	}

	count, err = Districts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
