// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testVoters(t *testing.T) {
	t.Parallel()

	query := Voters()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testVotersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Voter{}
	if err = randomize.Struct(seed, o, voterDBTypes, true, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Voters().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVotersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Voter{}
	if err = randomize.Struct(seed, o, voterDBTypes, true, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Voters().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Voters().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVotersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Voter{}
	if err = randomize.Struct(seed, o, voterDBTypes, true, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := VoterSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Voters().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testVotersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Voter{}
	if err = randomize.Struct(seed, o, voterDBTypes, true, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := VoterExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Voter exists: %s", err)
	}
	if !e {
		t.Errorf("Expected VoterExists to return true, but got false.")
	}
}

func testVotersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Voter{}
	if err = randomize.Struct(seed, o, voterDBTypes, true, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	voterFound, err := FindVoter(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if voterFound == nil {
		t.Error("want a record, got nil")
	}
}

func testVotersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Voter{}
	if err = randomize.Struct(seed, o, voterDBTypes, true, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Voters().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testVotersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Voter{}
	if err = randomize.Struct(seed, o, voterDBTypes, true, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Voters().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testVotersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	voterOne := &Voter{}
	voterTwo := &Voter{}
	if err = randomize.Struct(seed, voterOne, voterDBTypes, false, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}
	if err = randomize.Struct(seed, voterTwo, voterDBTypes, false, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = voterOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = voterTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Voters().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testVotersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	voterOne := &Voter{}
	voterTwo := &Voter{}
	if err = randomize.Struct(seed, voterOne, voterDBTypes, false, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}
	if err = randomize.Struct(seed, voterTwo, voterDBTypes, false, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = voterOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = voterTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Voters().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func voterBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Voter) error {
	*o = Voter{}
	return nil
}

func voterAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Voter) error {
	*o = Voter{}
	return nil
}

func voterAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Voter) error {
	*o = Voter{}
	return nil
}

func voterBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Voter) error {
	*o = Voter{}
	return nil
}

func voterAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Voter) error {
	*o = Voter{}
	return nil
}

func voterBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Voter) error {
	*o = Voter{}
	return nil
}

func voterAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Voter) error {
	*o = Voter{}
	return nil
}

func voterBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Voter) error {
	*o = Voter{}
	return nil
}

func voterAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Voter) error {
	*o = Voter{}
	return nil
}

func testVotersHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Voter{}
	o := &Voter{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, voterDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Voter object: %s", err)
	}

	AddVoterHook(boil.BeforeInsertHook, voterBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	voterBeforeInsertHooks = []VoterHook{}

	AddVoterHook(boil.AfterInsertHook, voterAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	voterAfterInsertHooks = []VoterHook{}

	AddVoterHook(boil.AfterSelectHook, voterAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	voterAfterSelectHooks = []VoterHook{}

	AddVoterHook(boil.BeforeUpdateHook, voterBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	voterBeforeUpdateHooks = []VoterHook{}

	AddVoterHook(boil.AfterUpdateHook, voterAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	voterAfterUpdateHooks = []VoterHook{}

	AddVoterHook(boil.BeforeDeleteHook, voterBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	voterBeforeDeleteHooks = []VoterHook{}

	AddVoterHook(boil.AfterDeleteHook, voterAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	voterAfterDeleteHooks = []VoterHook{}

	AddVoterHook(boil.BeforeUpsertHook, voterBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	voterBeforeUpsertHooks = []VoterHook{}

	AddVoterHook(boil.AfterUpsertHook, voterAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	voterAfterUpsertHooks = []VoterHook{}
}

func testVotersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Voter{}
	if err = randomize.Struct(seed, o, voterDBTypes, true, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Voters().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testVotersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Voter{}
	if err = randomize.Struct(seed, o, voterDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(voterColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Voters().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testVotersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Voter{}
	if err = randomize.Struct(seed, o, voterDBTypes, true, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testVotersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Voter{}
	if err = randomize.Struct(seed, o, voterDBTypes, true, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := VoterSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testVotersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Voter{}
	if err = randomize.Struct(seed, o, voterDBTypes, true, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Voters().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	voterDBTypes = map[string]string{`CreatedAt`: `timestamp without time zone`, `ID`: `integer`, `UpdatedAt`: `timestamp without time zone`}
	_            = bytes.MinRead
)

func testVotersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(voterPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(voterColumns) == len(voterPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Voter{}
	if err = randomize.Struct(seed, o, voterDBTypes, true, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Voters().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, voterDBTypes, true, voterPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testVotersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(voterColumns) == len(voterPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Voter{}
	if err = randomize.Struct(seed, o, voterDBTypes, true, voterColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Voters().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, voterDBTypes, true, voterPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(voterColumns, voterPrimaryKeyColumns) {
		fields = voterColumns
	} else {
		fields = strmangle.SetComplement(
			voterColumns,
			voterPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := VoterSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testVotersUpsert(t *testing.T) {
	t.Parallel()

	if len(voterColumns) == len(voterPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Voter{}
	if err = randomize.Struct(seed, &o, voterDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Voter: %s", err)
	}

	count, err := Voters().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, voterDBTypes, false, voterPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Voter struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Voter: %s", err)
	}

	count, err = Voters().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
