[psql]
  dbname    = "tern"
  host      = "localhost"
  port      = 5432
  user      = "tern"
  pass      = "tern"
  sslmode   = "disable"
  blacklist = ["core_store", "upload_file", "upload_file_morph", "users-permissions_permission", "users-permissions_role", "users-permissions_user", "migrations"]
